//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRecruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int stdid { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<int> TestMarks { get; set; }
        public Nullable<int> InterviewMarks { get; set; }
        public string Status { get; set; }
        public string Role { get; set; }
    }
}
